image: python:3.7

stages:
  - test

Test:
  stage: test
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    TRAVIS_OS_NAME: "linux"
    PYTHON_VERSION: "3.7"

    cache:
      paths:
        - .cache/pip
        - venv/

    before_script:
      - source script/conda.sh
      - conda create --yes -n test python="${PYTHON_VERSION}"
      - source activate test
      - pip install scipy
      - pip install codecov
      - python setup.py install

    script:
      - python setup.py test
      - codecov