name: CI

on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Set up Python 3.6.12
        uses: actions/checkout@v2
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.12
      - name: Run installation.
        run: source script/conda.sh
