name: CI

on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6.12
      - uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
          activate-environment: test
          python-version: 3.6
      - run: conda --version
      - run: which python
      - name: Run installation.
        run: |
         conda install -n test -y scipy
         conda install -n test -y -c conda-forge networkit
         pip install codecov
         python setup.py install
         coverage run setup.py test
         coverage xml -i
         echo "YOLO"
      - name: Code Coverage
        uses: codecov/codecov-action@v1
